# coding: utf-8

"""
    kappa-data

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import kappa_data_client
from kappa_data_client.model.create_function import CreateFunction
from kappa_data_client import configuration


class TestCreateFunction(unittest.TestCase):
    """CreateFunction unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
