# coding: utf-8

"""
    kappa-runner

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import kappa_runner_client
from kappa_runner_client.model.function_to_load import FunctionToLoad
from kappa_runner_client import configuration


class TestFunctionToLoad(unittest.TestCase):
    """FunctionToLoad unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
