# coding: utf-8

# flake8: noqa

"""
    kappa-data

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "0.0.0"

# import ApiClient
from kappa_data_client.api_client import ApiClient

# import Configuration
from kappa_data_client.configuration import Configuration

# import exceptions
from kappa_data_client.exceptions import OpenApiException
from kappa_data_client.exceptions import ApiAttributeError
from kappa_data_client.exceptions import ApiTypeError
from kappa_data_client.exceptions import ApiValueError
from kappa_data_client.exceptions import ApiKeyError
from kappa_data_client.exceptions import ApiException
