# coding: utf-8

"""
    kappa-logs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import kappa_logs_client
from kappa_logs_client.model.http_validation_error import HTTPValidationError
from kappa_logs_client import configuration


class TestHTTPValidationError(unittest.TestCase):
    """HTTPValidationError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
