# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import kappa_runner_client
from kappa_runner_client.paths.functions_load import post  # noqa: E501
from kappa_runner_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestFunctionsLoad(ApiTestMixin, unittest.TestCase):
    """
    FunctionsLoad unit test stubs
        Load Function  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
