# coding: utf-8

"""
    kappa-runner

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

from kappa_runner_client.paths.functions_fn_id_.get import ExecuteFunction
from kappa_runner_client.paths.functions_fn_id_is_loaded.get import IsFunctionLoaded
from kappa_runner_client.paths.functions_load.post import LoadFunction
from kappa_runner_client.paths.functions_fn_id_.delete import UnloadFunction


class DefaultApi(
    ExecuteFunction,
    IsFunctionLoaded,
    LoadFunction,
    UnloadFunction,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
