# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import kappa_fn_code_client
from kappa_fn_code_client.paths.code_code_id_ import get  # noqa: E501
from kappa_fn_code_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestCodeCodeId(ApiTestMixin, unittest.TestCase):
    """
    CodeCodeId unit test stubs
        Get Code  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
