# coding: utf-8

"""
    kappa-data

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

from kappa_data_client.paths.functions_.post import CreateFunction
from kappa_data_client.paths.functions_fn_name_.delete import DeleteFunction
from kappa_data_client.paths.functions_fn_name_.get import GetFunction
from kappa_data_client.paths.users_me_.get import GetMe
from kappa_data_client.paths.login_.post import Login


class DefaultApi(
    CreateFunction,
    DeleteFunction,
    GetFunction,
    GetMe,
    Login,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
