# coding: utf-8

"""
    kappa-data

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

from kappa_data_client.paths.bill_.get import Bill
from kappa_data_client.paths.functions_.post import CreateFunction
from kappa_data_client.paths.functions_fn_name_.delete import DeleteFunction
from kappa_data_client.paths.functions_fn_name_.get import GetFunction
from kappa_data_client.paths.functions_id_fn_id_.get import GetFunctionById
from kappa_data_client.paths.functions_fn_id_logs_.get import GetFunctionLogs
from kappa_data_client.paths.users_me_.get import GetMe
from kappa_data_client.paths.functions_fn_id_logs_execution_exec_id.post import LogFunctionExecution
from kappa_data_client.paths.login_.post import Login
from kappa_data_client.paths.signup_.post import Signup


class DefaultApi(
    Bill,
    CreateFunction,
    DeleteFunction,
    GetFunction,
    GetFunctionById,
    GetFunctionLogs,
    GetMe,
    LogFunctionExecution,
    Login,
    Signup,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
