# coding: utf-8

"""
    kappa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

from kappa_client.paths.functions_.post import CreateFunction
from kappa_client.paths.functions_fn_name.delete import DeleteFunction
from kappa_client.paths.functions_fn_name.get import ExecuteFunction
from kappa_client.paths.bill_.get import GetBill
from kappa_client.paths.functions_exec_exec_id_logs_.get import GetExecLogs
from kappa_client.paths.functions_fn_name_logs_.get import GetFnLogs
from kappa_client.paths.user_me.get import GetMe
from kappa_client.paths.login_.post import Login
from kappa_client.paths.signup_.post import Signup


class DefaultApi(
    CreateFunction,
    DeleteFunction,
    ExecuteFunction,
    GetBill,
    GetExecLogs,
    GetFnLogs,
    GetMe,
    Login,
    Signup,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
