# coding: utf-8

"""
    kappa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import kappa_client
from kappa_client.model.git_hub_response import GitHubResponse
from kappa_client import configuration


class TestGitHubResponse(unittest.TestCase):
    """GitHubResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
