# coding: utf-8

"""
    kappa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import kappa_client
from kappa_client.model.created_function import CreatedFunction
from kappa_client import configuration


class TestCreatedFunction(unittest.TestCase):
    """CreatedFunction unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
