# coding: utf-8

"""
    kappa-fn-logs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""

from kappa_fn_logs_client.paths.logs_.post import CreateLog
from kappa_fn_logs_client.paths.logs_fn_.get import GetLogs


class DefaultApi(
    CreateLog,
    GetLogs,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
